language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - 2.6
  - 2.7
  - pypy
install:
  - pip install -r requirements.txt
script:
  - python setup.py build
  - python setup.py test
